version: '3.8'
services:
  app:
    container_name: bot-backend
    build: .
    ports:
     - "8000:8000"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    